[project]
name = "LRE Result Extractor"
description = "A tool to extract and process results from LRE (Language Runner Enterprise) HTML page."
version = "0.2.0"
authors = [
    { name = "Nicolas N"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "beautifulsoup4",
    "openpyxl",
    "lxml"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"